(require 'recentf)
(recentf-mode 1)
(setq recentf-max-menu-items 25)
(global-set-key "\C-x\ \C-r" 'recentf-open-files)

(require 'cl)
(require 'eclim)
(setq eclim-executable "~/soft/eclipse/eclim")
(global-eclim-mode)

(setq ergoemacs-variant "master")
(ergoemacs-mode 1)
(ergoemacs-key "C-<tab>" 'hippie-expand "Hippie expand")

;;(let (prefix "M-1 ")
;;  (define-key eclim-mode-map (kbd (concat prefix "s")) 'eclim-java-method-signature-at-point)
  ;; (define-key eclim-mode-map (kbd "C-c C-e f d") 'eclim-java-find-declaration)
  ;; (define-key eclim-mode-map (kbd "C-c C-e f r") 'eclim-java-find-references)
  ;; (define-key eclim-mode-map (kbd "C-c C-e f t") 'eclim-java-find-type)
  ;; (define-key eclim-mode-map (kbd "C-c C-e f f") 'eclim-java-find-generic)
  ;; (define-key eclim-mode-map (kbd "C-c C-e r") 'eclim-java-refactor-rename-symbol-at-point)
  ;; (define-key eclim-mode-map (kbd "C-c C-e i") 'eclim-java-import-organize)
  ;; (define-key eclim-mode-map (kbd "C-c C-e h") 'eclim-java-hierarchy)
  ;; (define-key eclim-mode-map (kbd "C-c C-e z") 'eclim-java-implement)
  ;; (define-key eclim-mode-map (kbd "C-c C-e d") 'eclim-java-doc-comment)
  ;; (define-key eclim-mode-map (kbd "C-c C-e f s") 'eclim-java-format)
  ;; (define-key eclim-mode-map (kbd "C-c C-e g") 'eclim-java-generate-getter-and-setter)
;;)
